version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**/*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: P8cmu7BZh3GOr+3bq5NVZEAEGnvjyC1wKhEmk4pcfTxiZwP7qS2t0pTPPn+q4ILC
  artifact: '**/*.nupkg'
  on:
    branch: master

test_script:
 - dotnet test GeneGenie.DataQuality.Tests/GeneGenie.DataQuality.Tests.csproj /p:AltCover=true /p:AltCoverAssemblyExcludeFilter=GeneGenie.DataQuality.Tests
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "GeneGenie.DataQuality.Tests/coverage.xml" -t $Env:CODECOV_TOKEN
